### ISSUE TITLE
Suggestion: More exposed station file commands

### ISSUE THREAD

**Issue by Mezign** [voxeltycoon/suggestions#114]
More control over road and rail station parameters in the mod-able files (min/max length, capture radius, stop at end or centred, etc), and having stations placement boxes defined by their connected objects rather than default platform size area. This would allow "invisible" stations to use the least amount of land area and be decorated as the user sees fit.

I would also like to be able to utilise stations as a pass through command, similar to how modders created signal boxes as waypoints for TTD (and OTTD).

**Comment by andrewpey** [comment]
@Mezign could you please split this to more specific issues, eg:
* Allow setting min/max station length in assets
* Allow setting station capture radius in assets
* Allow using placement boxes defined by station connected objects rather than default platform size area
* etc...

Thanks!

**Comment by Mezign** [comment]
@andrewpey , sure. What you've suggested is pretty much what I had in mind. To confirm:

- Allow setting min/max station length in assets (Suggest: min 5m to max 250m range).
- Allow setting station capture radius in assets (Suggest: 0 to default)
- Allow using placement boxes defined by station connected objects rather than default platform size area (This explains it perfectly).
- Allow in Station menu options to stop at end of platform (default), or stop centered.
- Allow Pass Through train schedule command on stations ("Go Via" in TTD).
- Allow setting in station assets for trains to move and stop to load only cars that are on station tiles. (Eg. Coal train flood loader). (Suggest; Station Type: "Car Loader/Train Loader")

**Comment by andrewpey** [comment]
What I meant is there should be separate 'tickets' for each of this issue 😉 

Btw, the first one is already done in [0.80](https://voxeltycoon.xyz/changelog#80).

**Comment by victorleblais** [comment]
> - Allow setting min/max station length in assets (Suggest: min 5m to max 250m range).
> - Allow setting station capture radius in assets (Suggest: 0 to default)
> - Allow Pass Through train schedule command on stations ("Go Via" in TTD).

As of 0.85, those are now in the game and like andrew said, some were even implemented earlier.

I'll add that it's possible to specific a maximum number of tracks for a station too, and you can also have a lot more control on assets used to decorate the various parts of the stations.
