### ISSUE TITLE
Borderless Window

### ISSUE THREAD

**Issue by randoomx8** [voxeltycoon/suggestions#115]
I consider this feature to be essential, I hope it gets added into the game.

**Comment by victorleblais** [comment]
The "Fullscreen" option **is** borderless.

There is no "real" fullscreen option though.

**Comment by victorleblais** [comment]
And you can decide if the cursor is locked to the game window: 
![image](https://user-images.githubusercontent.com/4365075/78130787-3bd4e080-741a-11ea-95f6-5a8fce8db7cf.png)
