### ISSUE TITLE
ResearchURI for .rail and .raildepot

### ISSUE THREAD

**Issue by klutz-goldenarrow** [voxeltycoon/suggestions#118]
Part issue, part bug.

.rail has a ResearchUri option. However, it might not work. I've attached a copy of my mod which has the line:
  "ResearchUri": "base/rails_3.research",

It should not be possible to use it without this being researched. 

However, the screenshot below shows that Rails 3 is unresearched, that my Depot Rails are unlocked by the research _and_ that I'm still able to use Depot Rails.

![image](https://user-images.githubusercontent.com/38834964/78289153-9b65e580-7519-11ea-97f4-14a5a0c54744.png)

[depot_rails.rail.txt](https://github.com/voxeltycoon/suggestions/files/4423007/depot_rails.rail.txt)

I think it may be caused by the fact I've used Depot Rails in my .raildepot mod.

.raildepot doesn't allow for ResearchUri to be used. This might then override the need for researching the rails.

I tested this theory by setting the ResearchURI for the base game rails to rails_2.research and was able to use them straight away in a new game.

**Comment by andrewpey** [comment]
Fixed in [0.84](https://voxeltycoon.xyz/changelog#0.84).
