### ISSUE TITLE
Suggestion: Transport Routes - dont delete if nothing is assigned

### ISSUE THREAD

**Issue by HolgerVornholt** [voxeltycoon/suggestions#128]
A Route currently gets automatically removed when no vehicle is assigned to it.
Add the option to remove a route as a new item next to "rename".

It can be necessary to temporarily switch all vehicles of one route to another and back. Especially at the start of a game.

**Comment by victorleblais** [comment]
Routes are no longer removed when the last vehicle on it is removed.
