### ISSUE TITLE
Do not close or unselect decorations after placing one

### ISSUE THREAD

**Issue by victorleblais** [voxeltycoon/suggestions#13]
**Is your feature request related to a problem? Please describe.**
With mods that add decoration, such as TransCanadaLimited's signals (that include posts, supports and ground decoration), it is extremely tedious to open the menu, scroll down, find the item, place it, and repeat it all again. It's especially bad when placing the ground decoration (additionnal basalt between tracks), and I'm guessing this will be an issue when other mods also provide decoration that is "intended" to be place multiple times over a large area.

**Describe the solution you'd like**
When placing a decoration, it should not "clear the cursor" of the item and it should not close the window.
Pressing Escape would clear the cursor.
Pressing escape a second time would close the decoration window.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by victorleblais** [comment]
@polak-jan I guess this could technically be closed since you can now hold shift to build the same item multiple times.

There's still room for improvement though, but that's better covered by #5

**Comment by polak-jan** [comment]
I guess it can, closing but will add a reference to #5
