### ISSUE TITLE
Suggestion: buildings catchment area.

### ISSUE THREAD

**Issue by scailman** [voxeltycoon/suggestions#130]
Add a button in industries, warehouses and train and truck stations  windows to activate / deactivate the catchment area.
Once one of these buildings is placed sometimes you need to see the catchment area to put more buildings in range.
It's a small quality of life feature.

![image](https://user-images.githubusercontent.com/60572000/81401017-ad493280-912e-11ea-8b8c-fb991007dc6f.png)

**Comment by drewtato** [comment]
This does have a full workaround (except for industries): hold the build tool for the building on top of it.

**Comment by andrewpey** [comment]
Actually, we already have such a feature - even the button was planned to be in the same place - in our backlog. Thank you!

**Comment by victorleblais** [comment]
This feature is now added with the new Logistics view.
When you click on the Logistics tab of a building, you can see the building in range and also lines that indicates connections (and if they're active or not)
![image](https://user-images.githubusercontent.com/4365075/115537437-1b80f980-a29b-11eb-9965-a983a0370aaa.png)
