### ISSUE TITLE
Display distance to nearest signal/junction when placing a signal

### ISSUE THREAD

**Issue by daiwai** [voxeltycoon/suggestions#144]
When placing a new signal, it would be nice to easily see the distance to the nearest signal or junction in both directions of the new signal. This would help when wanting to enforce a certain distance between signals in your network.

It could look something like this:
![signal_distance_overlay](https://user-images.githubusercontent.com/683371/90338740-1113af00-dfec-11ea-92d7-e50399aa8823.png)

**Comment by victorleblais** [comment]
Very good suggestion, and nice mockup.
I'm not sure your design is easy to do and/or easy to read in some cases (on curves, or when there are tracks or other objects "in the way" of your "tooltip").
Worst case scenario, it could be added in the price tooltip...
