### ISSUE TITLE
One way road

### ISSUE THREAD

**Issue by LokutusPokutus** [voxeltycoon/suggestions#152]
I absolutely LOVE the game but I would like to have a one-way road so it won't get so jammed when one drags roads and place stations. 
![2021-01-13 (5)](https://user-images.githubusercontent.com/77415758/104515530-3e907300-55f3-11eb-83e9-532b5edccbe6.png)
![2021-01-13 (4)](https://user-images.githubusercontent.com/77415758/104515549-45b78100-55f3-11eb-97e4-009d4ea64859.png)

I hope you guys keep up the good work and take care!
Much love from Loke

**Comment by victorleblais** [comment]
Announced as planned in the roadmap and FAQ:
![image](https://user-images.githubusercontent.com/4365075/115476826-ef398e80-a242-11eb-8ec1-f33986772971.png)
https://voxeltycoon.xyz/devlog/ea-faq/
https://voxeltycoon.xyz/roadmap

**Comment by victorleblais** [comment]
Duplicate of #100
