### ISSUE TITLE
Selling to demand without vehicles

### ISSUE THREAD

**Issue by polak-jan** [voxeltycoon/suggestions#17]
# Suggestion
My idea on how this could be achieved would be using a separate building, a sort of "Market", that would try to sell all goods it has in it's storage to nearby demands, each market could only sell one type of goods, or maybe later the player could unlock bigger ones (supermarkets, hypermarkets) via research. Even the first market would be locked behind a research node though to balance it a bit.

**Comment by victorleblais** [comment]
To combine a bit of all the ideas here:

- Make a market that acts like a warehouse.
- It has a GUI to select which resources/business it will sell to.
- The building is unlocked by research (that should be around the mid-tier I guess)

**Comment by Garagoth** [comment]
There is already most of this in place in warehouses and logistics. It needs a bit of small additions:
- allow industries to take needed goods from warehouses in range using logistics (like from stations and how Lab works)
- add weights and priorities to logistics connections (for example 3/5 of goods to industry A, 2/5 to B)

Warehouses can be already fed by vehicles via stations and directly by conveyor belts, optionally add an option for a conveyor belt connector to feed goods to stations (and goods will be stored in connected warehouse) (see also voxeltycoon/bug-tracker#203), but this depends on your vision where conveyor belts end and logistics begin (as those can overlap in functionality a bit).

**Comment by MajorFordson** [comment]
Allow me to +1 the idea of a mid-game building for delivering goods through a city, without the player having to set up a dozen trucks and truck stops. Being able to simply set up an area of effect building to sell goods that arrive on, say a mixed goods freight train into a train station, would be perfect for players who don't want to micro manage an entire fleet of trucks in every city. You can even slightly penalise such an idea by taking a percentage of the sales for the distributors.

For such a system it would be really nice to see delivery vans (not trucks) coming and going from such a distribution building out to each business, like delivery carriers in many city builder games.

**Comment by Tenybras** [comment]
I was completely confused that this was not the case, so for me it looked like a Bug and it halted my gameplay.

I see that a business is connected to a station and the station has the needed goods.
![image](https://user-images.githubusercontent.com/39140051/115861889-b3b1e680-a433-11eb-8379-624baea0b108.png)
![image](https://user-images.githubusercontent.com/39140051/115861921-bdd3e500-a433-11eb-8141-c7c411912973.png)
As you can see it _states_ it is outputting to the other building

To fix this I had park a car forever in front of the Station, which picked up 5 items from the Station and put them back in the station to be delivered.
Either the tutorial or tooltip should state that Goods can not be deliver to businesses without trucks
![image](https://user-images.githubusercontent.com/39140051/115862199-202ce580-a434-11eb-842c-c039683e64e3.png)

Request for a thread label to be added either one of these that would deemed fit by the developer: Bug/documentation/gameplay.

**Comment by greeny** [comment]
> As you can see it states it is outputting to the other building

@Tenybras yes, the **station** is outputting to a building, not the warehouse.
