### ISSUE TITLE
Include city name in Business' window

### ISSUE THREAD

**Issue by victorleblais** [voxeltycoon/suggestions#178]
_Suggestion from Kershek#9103 on Discord._

There is no way to know in which city a business is in its detail window. You can click on the icon in the title to move your camera there, but if you have several windows opened and need to see which one is where at a glance, you can't.

It could be solved by including the city name in this window, either in the title or somewhere near the city level progress. The second one could be confusing since one could think the level is the city level instead of the business level.

Here's a mock-up I made:

![image](https://user-images.githubusercontent.com/4365075/114991729-35d16680-9e9a-11eb-8a3e-0cda645128d0.png)

**Comment by Fredrik-Leftin** [comment]
I think it's better put the city name out the black zone (that could become too busy to read). Also, I re-suggest to add for each town name an abbreviation (e.g.: San Benedetto del Tronto  +  S. Benedetto del T.) .
This strategy can easily resolve some problems caused by these long names.

**Comment by victorleblais** [comment]
Duplicate of #54
