### ISSUE TITLE
Clickable UI for tool options (suggested by u/Moratamor on Reddit)

### ISSUE THREAD

**Issue by polak-jan** [voxeltycoon/suggestions#18]
**Is your feature request related to a problem? Please describe.**
Currently there is no way to change parameters of a tool other than hot keys, apparently some people prefer to use the mouse only,

**Describe the solution you'd like**
My idea on how to fix this would also fix the issue of people not noticing the hints on the bottom right. Basically changing it to a window with background so it's more noticeable and making the key images clickable.

**Describe alternatives you've considered**
Rework it entirely. But I don't think that would be exactly a great idea.

**Additional context**
https://www.reddit.com/r/voxeltycoon/comments/c7at82/can_we_get_ui_for_station_lengthwidth_etc/

**Comment by andrewpey** [comment]
Yeah, we plan to have UI for all tools, with hotkeys-only approach only as a temporary solution. We already added UI for signal type picking in `0.73`, and windows for other tools will be added in the near feature.
