### ISSUE TITLE
"Looking for Trouble" should be "Troubleshooting" in English (idiom)

### ISSUE THREAD

**Issue by madamehardy** [voxeltycoon/suggestions#190]
Whenever I add a new truck, the UI pops up "Looking for trouble".  In American English, "looking for trouble" usually means "trying to get into a fight" or "trying to commit a crime".  A better translation would be "Troubleshooting"  (idiom for figuring out why a computer is doing something wrong) or perhaps "Looking for errors".

**Comment by polak-jan** [comment]
The "trying to get into trouble" meaning is the correct one, as the vehicle doesn't know what to do, which often ends in trouble. It's a little bit of a joke. But thanks for the report, if you find something else please do let us know.
