### ISSUE TITLE
COPY & PASTE (Railways, Crossings, Signalling)

### ISSUE THREAD

**Issue by Eirikfesker** [voxeltycoon/suggestions#191]
I wish a possibilty to copy and paste e.g. track layouts. Railroad-Crossings with signalling and so on! The time to build advanced layouts is very time consuming.

**Comment by victorleblais** [comment]
Blueprint feature is planned. https://voxeltycoon.xyz/roadmap

Please make sure to check out the roadmap (and even posts here, there's a search bar) before posting.
