### ISSUE TITLE
Allow total refund of buildings in pause mode

### ISSUE THREAD

**Issue by madamehardy** [voxeltycoon/suggestions#192]
Right now, I can't experiment with where to place, say, a station, because it costs me $23090 to place the station, but I only get back $6927 if I delete it.   This means that when I build a building that can't be reached by road, something I can't always determine in advance, I lose money.  Building the roads first isn't always the answer, because I need to determine where to place the station relative to the demand for goods.

I'd really like a planning mode, where I could lay out buildings and roads without committing to them until I explicitly say so, but second best would be if you aren't charged for buildings/roads/train tracks when in pause mode, and the charges are made when you unpause.

**Comment by victorleblais** [comment]
There a difficulty setting when creating a world that allows full refund when building.
![image](https://user-images.githubusercontent.com/4365075/115076696-394a0980-9efd-11eb-8d49-cf801973b858.png)

Also, the planning mode is on the roadmap https://voxeltycoon.xyz/roadmap
There's #47 for that
![image](https://user-images.githubusercontent.com/4365075/115076763-4ebf3380-9efd-11eb-8e03-091dcc479556.png)
