### ISSUE TITLE
Water/ship related resources

### ISSUE THREAD

**Issue by lshaf** [voxeltycoon/suggestions#196]
- Ship of course
  - can moving resource via ship like passenger or other resource?
- Oil from water
- Fishing resource
- Drinking water?
- Shells
- Farm in water maybe?

**Comment by victorleblais** [comment]
Ships are planned. But I'm not sure how much of the other things you have listed are planned.

**Comment by lshaf** [comment]
Thanks for correcting mate.
I don't know it was planned but when I look up for "water" keyword it doesn't come with any result 😁.
