### ISSUE TITLE
Visual flag on intersections that don't connect

### ISSUE THREAD

**Issue by madamehardy** [voxeltycoon/suggestions#204]
It is easy (at least for me) to drag one road onto another and miss that they aren't actually connected.  This is especially tricky when connecting a bridge to a road, where the small white line between the roads is partly masked in some orientations.   Could you put in a visual cue when one road ends next to another, but they aren't connected?  Maybe something like an X on the blocked road?  

It's a lot easier to debug when I can easily spot that two connected roads aren't.

Roadmap with unreachable path warning:
![image](https://user-images.githubusercontent.com/4690758/115129086-92667b80-9f97-11eb-94f9-5bfafb6c138d.png)

Close-up of the intersection that doesn't intersect, below Akron Annex:
![image](https://user-images.githubusercontent.com/4690758/115129093-a9a56900-9f97-11eb-84c4-7aa8cefd0168.png)

(Thanks to UGH Dany on Discord for debugging the problem.)

**Comment by polak-jan** [comment]
This seems more like a bug to me as that road configuration shouldn't be possible to build in the first place. The road system still has quite a few quirks like this to it tha need ironing out so we will make sure this one is noted down. Closing but feel free to comment if you do not agree.
