### ISSUE TITLE
Lack of explanation between Semaphores and electric signals

### ISSUE THREAD

**Issue by andbruu** [voxeltycoon/suggestions#235]
Having only semaphores or both (+1 electric signals) available from start is part of the difficulty setting, but one setting allows me to build the cheap option (semaphore), and the other option allows me to build both.
I conclude that the option that allows both must be the easier difficulty option, but I do not know why.

This have left me to believe that the electric signal must have an advantages over the semaphore, as it normally require research and is more expensive to construct.
I would love that the tooltip makes it clear what advantages the electric signals provide.

**Comment by victorleblais** [comment]
I'd argue that the only advantage of signals with lights is that they're easier to understand at a glance. But they work exactly the same.
