### ISSUE TITLE
Suggestion: Rairoad Crossing + other 

### ISSUE THREAD

**Issue by klo3** [voxeltycoon/suggestions#241]
It would be a relief for city building and some other factory management if we would be able to cross roads with railroads.
Same as beeing able to build curves on bridges (conveyor, street and railroads)

Love the Game :)

**Comment by victorleblais** [comment]
This is planned on the roadmap: https://voxeltycoon.xyz/roadmap
![image](https://user-images.githubusercontent.com/4365075/115476212-b64cea00-a241-11eb-8a9e-25cf68310d03.png)

This is also described in the Early Access FAQ:
https://voxeltycoon.xyz/devlog/ea-faq/
![image](https://user-images.githubusercontent.com/4365075/115476240-c8c72380-a241-11eb-8d6d-7daab7dac741.png)
