### ISSUE TITLE
Suggestion: Show path preview when editing routes

### ISSUE THREAD

**Issue by Blastxu** [voxeltycoon/suggestions#243]
It would be nice to see a preview of the path a vehicle will take when traveling along an established route. Plus, it would also show you when you forgot to connect a road or rail.

Example, Cities skylines route path UI for different vehicle types:
![image](https://user-images.githubusercontent.com/11802194/115327091-33456a00-a143-11eb-82b6-5f4f1a9c969b.png)

**Comment by victorleblais** [comment]
Duplicate of #40
