### ISSUE TITLE
Suggestion: electricity generation and distribution

### ISSUE THREAD

**Issue by kiwinuken** [voxeltycoon/suggestions#245]
This would add depth to the game. Industry and towns could require electricity, which the player could produce and provide through its specific distribution lines. Obvious start is coal, but oil, gas and nuclear can easily follow, with its respective resources. Solar and wind, and even hydro - if water physics and dams are implemented - would actually enable the proper narrative to implement another big thing: climate change dues to emission of greenhouse gases.

Well, that escalated quickly. Just energy generation and distribution is a good start.

**Comment by victorleblais** [comment]
This is planned
![image](https://user-images.githubusercontent.com/4365075/115476007-2e66e000-a241-11eb-99aa-de595da7b1ff.png)

Water physics is also planned, oil is also planned
![image](https://user-images.githubusercontent.com/4365075/115476032-40e11980-a241-11eb-8c53-9ae333808598.png)
![image](https://user-images.githubusercontent.com/4365075/115476052-4a6a8180-a241-11eb-95d6-850c097c1a8e.png)


Please check the roadmap before making suggestions.

**Comment by kiwinuken** [comment]
OMG, I totally missed the electricity card! I saw the others, but I didn't see the main one. Sorry.
