### ISSUE TITLE
Extend stations without deleting.

### ISSUE THREAD

**Issue by Matschgo97** [voxeltycoon/suggestions#249]
When placing a station with only one platform and later expanding it to more platforms, it'd be great to extend the station by just placing another platform next to it (without deleting the original one).
Same applies for single and double bus stops.

![screenshot](https://user-images.githubusercontent.com/82895757/115428060-4cf9b680-a202-11eb-8c5b-b3fafd3b5bd5.png)

**Comment by victorleblais** [comment]
Duplicate of #27
