### ISSUE TITLE
Update schedule if a removed station is replaced fast enough

### ISSUE THREAD

**Issue by MaximDementyev** [voxeltycoon/suggestions#25]
**Is your feature request related to a problem? Please describe.**
if you remove the railway station and immediately put in its place another, the trains lose the route point

**Describe the solution you'd like**
add the mechanics, as in shipping fever. if the new station was built fast enough and close to the previous location, the route contains the point of the previous station on its way, will automatically change it to the new station

**Describe alternatives you've considered**
show context menu with question "do you need to change point to new in all routes?"

**Additional context**

**Comment by JapaMala** [comment]
Yeah, this is one of those features that has been really missed by me during my playthrough. That, and the ability to upgrade stations, but both are imporant separately.

**Comment by victorleblais** [comment]
Implemented in 0.76 (2019-08-15)
