### ISSUE TITLE
Greater distances between cities

### ISSUE THREAD

**Issue by Frozen-Rainbow** [voxeltycoon/suggestions#270]
It is a common problem for video games. Everything has to be packed closely together due to limited system resources.
Nevertheless it would be great if the cities would have much more "space" between each other.
Maybe you could reduce the number of cities and let them grow bigger instead.

**Comment by polak-jan** [comment]
You can already increase distances in general by making areas bigger. Not sure if there is any special that could be implemented for cities so I think the existing solution is more the enough. As such I am closing this issue, but if you do not agree feel free to comment bellow and we can reopen it.
