### ISSUE TITLE
CHF: Unrealistic prices

### ISSUE THREAD

**Issue by Frozen-Rainbow** [voxeltycoon/suggestions#271]
Yes, in Switzerland "everything" is more expensive than anywhere else. But in the game the price scaling is unrealistic.
Example Sawmill:
USD: 67 275
EUR: 60 548
CHF: 5 045 625

In fact, the CHF price for a sawmill is more adequate than the prices in USD and EUR. But the double bus stop with about 4,5 millions Swiss Francs is way too overpriced. A realistic price would be around CHF 100 000 to 200 000.

**Comment by polak-jan** [comment]
This isn't really a suggestion but a bug report, but even more importantly this is already fixed on the today announced beta branch so I am closing this issue. Thanks for reporting anyway though.
