### ISSUE TITLE
Swedish names

### ISSUE THREAD

**Issue by Vildravn** [voxeltycoon/suggestions#278]
Hey,
I thought I'd suggest/contribute some Swedish names, since the game already has SEK as a currency :)

[se.names.zip](https://github.com/voxeltycoon/suggestions/files/6366473/se.names.zip)

![image](https://user-images.githubusercontent.com/1076814/115896139-634e7f00-a45b-11eb-9e56-c777d7a4399b.png)

Thanks if you consider adding it.

**Comment by andrewpey** [comment]
Added in [0.85.1](https://voxeltycoon.xyz/changelog#0.85.1), thank you!
