### ISSUE TITLE
Valuing unpaid trips to prevent transfer routes from being declared unprofitable

### ISSUE THREAD

**Issue by Mikey5887** [voxeltycoon/suggestions#305]
The idea is not to be paid for factory -> warehouse trips but only to value it on the vehicle (a bit like OpenTTD for transfers)

**Comment by Mikey5887** [comment]
The idea is not to be paid for factory -> warehouse trips but only to value it on the vehicle (a bit like OpenTTD for transfers)

**Comment by JezzyBelle** [comment]
I agree that it is disturbing to see some trains that supply everything to my supply chain still get complaints over lack of income.
