### ISSUE TITLE
Installing a mod shouldn't reset scroll in the mod browser

### ISSUE THREAD

**Issue by MaximDementyev** [voxeltycoon/suggestions#33]
**Describe the bug**
after installing the mod in the mod browser, the scroll page rises to the top. very uncomfortable. you always have to scroll down.

**Steps to reproduce**
install any mod in the mod browser

**Build version**
pre-alpha

**Platform**
windows 10

**Reproducibility**
every time

**Comment by victorleblais** [comment]
Not relevant anymore since the game now uses the Steam Workshop
