### ISSUE TITLE
Add tooltip for rail signals

### ISSUE THREAD

**Issue by aLegoz** [voxeltycoon/suggestions#38]
**Is your feature request related to a problem? Please describe.**
It will add more information on screenshots. This will help to show problem(for bug report) or share railroad configuration to another person. 

**Describe the solution you'd like**
I want to see tooltip for rail signals.

**Additional context**
Example: 
![](https://i.imgur.com/0y9BhdX.png)
![](https://i.imgur.com/X8nfYcl.png)

**Comment by victorleblais** [comment]
@polak-jan Shouldn't this be marked as resolved/done and closed?

The Pre-Alpha 0.73 added this mode when building signals:
![image](https://user-images.githubusercontent.com/4365075/61202484-e881fd00-a6e7-11e9-8fc3-29643f3ec947.png)

(Image taken from [Voxel Tycoon's twitter](https://twitter.com/VoxelTycoon/status/1149297256648138752))

**Comment by polak-jan** [comment]
Yes it should, I didn't have to to go through the issues after 0.73 yet, thanks for reminding me.
