### ISSUE TITLE
Signals on long stretch of rail

### ISSUE THREAD

**Issue by c-herse** [voxeltycoon/suggestions#44]
Don't know if it has already been suggested but a way to place signals on a long stretch of rail.
Just like in the game "Railway Empire" where you can hold SHIFT, i think, and it places signals on the entire stretch of rail.
This would save tons of time when making long railways.

**Comment by victorleblais** [comment]
OpenTTD also allows this. It's a life saver, especially with the ability to choose the spacing distance in between signals.

**Comment by javorszky** [comment]
Came to the repository to post this, searched, found it, and :+1:'d!

**Comment by victorleblais** [comment]
You can now do that in 0.85 !

![image](https://user-images.githubusercontent.com/4365075/114952876-7fe52880-9e57-11eb-9bdf-cb95ad74a0e3.png)

There's even a shortcut that you can rebind in the settings.
