### ISSUE TITLE
Train reverse option

### ISSUE THREAD

**Issue by MountainDan** [voxeltycoon/suggestions#56]
Can we have the option to allow trains to reverse down lines, as opposed to only having turnaround option

**Comment by victorleblais** [comment]
In my opinion, if a train has a locomotive on each end, it should be able to "reverse" without having to actually "turnaround" (which applies a "timer/penalty").

It could make terminal-style stations more viable.

**Comment by YohDeadfall** [comment]
Another good idea is decoupling a loco from the train and connecting it on the other end. A turntable could be used to rotate the loco, or it could move backward which in case if it's supported by the loco design.

**Comment by victorleblais** [comment]
What you're describing would fall into the "shunting" feature. It is planned for the stage 3 of Steam Early Access, so it's quite far away.

https://trello.com/c/SqtrMpp3/41-shunting

**Comment by victorleblais** [comment]
This feature is planned to be implemented before Steam Early Access. It is listed as "Shuttle trains": https://trello.com/c/EIfKhWhX/23-shuttle-trains so I think this applies to what I described earlier: trains that can reverse without "flipping/inverting".

**Comment by victorleblais** [comment]
Shuttle trains are implemented.
