### ISSUE TITLE
More control over notifications

### ISSUE THREAD

**Issue by lehresman** [voxeltycoon/suggestions#57]
There are too many notifications that I don't care about.  So many that I've just started ignoring them.

One of my cities got starved for resources because of a train deadlock, and I didn't notice because I had tuned out the notifications.

Suggestions for improvement:
* Only notify about industries/businesses that you are supplying
* Have a way to watch an industry/business that I may care about in the future

**Comment by juffanoodle** [comment]
Maybe split the notifications out into categories, instead of having them all in one list? 

* Lost vehicles
* Starving businesses
* New businesses
* Increased capacity
* Research
* ....

**Comment by victorleblais** [comment]
I'm going to make a mix of both suggestions:

Have a "global" notification settings where you can toggle on/off notifications about:

- Lost vehicles
- Starving businesses
- New businesses
- Increased capacity
- Research
- Resource depletion
- ...

**and** also have a new tab on detail windows of cities where you can:

- See a list of all businesses in that city and you can select for each:
    - No notification at all
    - Minimal notification (only when the business is about to close down)
    - All notifications (increase/decrease of demand)
- and also three buttons "Set for all" that applies the same setting (none/minimal/all) to all business at once

That way you can entirely mute cities that you don't care about, and also mute "variations" in demand of cities that you already service, but don't care about the details of it (you just want to know if businesses are going to close); meanwhile you still have the possibility to be up to date of all changes on a few businesses that you're actively trying to grow.

**Comment by int3ger** [comment]
Dealing with notifications could also be made more friendly by removing their ability to forcefully move your current map view and instead popup the dialog for the given city, business, vehicle etc whereby we can CHOOSE to travel to that destination via another click or just take care of the issue via the dialog box. Provide a setting so this could be enabled/disabled as desired.

**Comment by victorleblais** [comment]
You can now have a setting to ignore supplying notifications for buildings you don't service (or all buildings):
![image](https://user-images.githubusercontent.com/4365075/115538604-5c2d4280-a29c-11eb-9e7e-ade6fde2f231.png)

You can also ignore a vehicle's notifications
![image](https://user-images.githubusercontent.com/4365075/115538704-736c3000-a29c-11eb-8145-a0ae8134e527.png)

I'm renaming the issue to reflect the desire to have even more granular control on this
