### ISSUE TITLE
Combine the refit order into the load order

### ISSUE THREAD

**Issue by regstar** [voxeltycoon/suggestions#59]
I like the new implementation for the refit button, but after playing with this I think about this implementation a bit.

At my option, it is a bit confusing when many stations to load, unload and refitting is on your schedule. I like the idea to implement the same 'choose your cargo' like behind the refit button on the loading button. 

On your schedule you can do something like this:
Station X: Load stone
Station Y: Unload
Station Y: Load iron
Station Z: Unload

This should be getting rid of nasty schedule plans.

Maybe it's a good thing to think about it to implement both. If someone wants to do this on another station or on the truck depot.

**Comment by noahjsc** [comment]
This was asked for in 2019, this would make life so much easier. Not having this nearly made me quit the game.

**Comment by victorleblais** [comment]
You can just do "Refit to X", "Load" and it works identically
![image](https://user-images.githubusercontent.com/4365075/115539745-a105a900-a29d-11eb-9cfd-c602bd318b42.png)
