### ISSUE TITLE
Color Blind Options

### ISSUE THREAD

**Issue by anthonycl** [voxeltycoon/suggestions#66]
For individuals such as myself who are colorblind or partially colorblind (about 7% of the male population) generally, Voxel Tycoon has amazing graphics and colors. One issue I have found recently is in the functionality to select which track is active on a station. I cannot tell which track is selected. My suggestion would be to make it very easy to determine would be to light the selected track in green and keep the others greyed, this is up to the dev team of course. I will post further findings when I encounter them.

Thanks for an amazing game so far!

**Comment by victorleblais** [comment]
Thanks a lot for your feedback.

Make sure to edit or add more comments when you find places in the game where it's hard to distinguish stuff because of color-blindness.

**Comment by andrewpey** [comment]
In 0.76, we've introduced basic theming support. The game now comes with optional colorblind-friendly color scheme that should help you with the issue described.

Please give it a try and let us know if we can improve it further!

**Comment by anthonycl** [comment]
Looking amazing so far! I will test more functionality over the next few
days.
