### ISSUE TITLE
Improve turn around by destination

### ISSUE THREAD

**Issue by hsungha** [voxeltycoon/suggestions#67]
When stations are all connected back and forth, Train does not turn around in place.
see descriptions : https://github.com/voxeltycoon/bug-tracker/issues/131

As you can see from the issue above, trains can reach faster when they are turned around between stations, but trains do not turn around when the station is connected by a circular track. Even trains travel more distances to reach their destination.

I got an answer saying that this was intended, and it's not a bug. However, this intention makes the game more cumbersome, so I suggest.

List I felt strange personally:
1) If this is considered, I do not understand that trains with locomotives on both sides do not go straight to the fast path.

Trains with locomotives on both sides do not need to turn around, so even if the end of the station is connected to a circular track, the train must go straight to the fastest route. But not in the game.

2) I saw an example of openttd in the above issue, but even in openttd the train will turn around quickly if the round track is connected long and go straight ahead.

Also, the screenshots as examples of explanation are not what I intended. 

![2019-08-06 (2)](https://user-images.githubusercontent.com/17085696/62494139-b9097080-b80d-11e9-8a93-65ff3b3d8294.png)
Here is what I connected in voxel tycoon. and in this connection, the train runs straight between the station and the station.

**Comment by polak-jan** [comment]
I certainly agree that trains with engines on both sides should behave this way.

**Comment by victorleblais** [comment]
As of 0.76 release, you can now choose which behavior you want (turning around or continuing straight ahead) thanks to the new task available in the vehicle's orders.
