### ISSUE TITLE
Set Fonface, Size for UI

### ISSUE THREAD

**Issue by oliverfuxx** [voxeltycoon/suggestions#74]
UI fonts in Main Menu and In-Game  look small and difficult to read. Can in the game be configured to change fonts or change size

https://cdn.discordapp.com/attachments/612594725509136387/613302290119393290/unknown.png

**Comment by victorleblais** [comment]
I'm pretty sure you've seen that but as a workaround, you can currently increase the entire UI's size.

But I agree that a font-only scaling option could be nice, especially in your case where non-latin characters can be smaller due to the font used.

**Comment by oliverfuxx** [comment]
OK, I can try.

**Comment by victorleblais** [comment]
Closing this since you can change the UI size in the settings
