### ISSUE TITLE
Rail signal overlay

### ISSUE THREAD

**Issue by slavfox** [voxeltycoon/suggestions#9]
**Is your feature request related to a problem? Please describe.**
Signals are a big point of confusion in the community. I personally have given up on using trains because I could never understand how they work. 

**Describe the solution you'd like**
Railway Empire, a favorite game of mine, has a very simple overlay that shows the effect of signals on train pathing:
![railwayempire](https://user-images.githubusercontent.com/35173529/60719670-b70b7380-9f28-11e9-837e-2f308ef898cb.gif)

Something similar for Voxel Tycoon would be great, an overlay that displays signal blocks to be triggered eg. while placing signals.

**Describe alternatives you've considered**
A clear in-game explanation of signal mechanics would be useful, but I think the overlay would be a great aid for clarity and the train learning curve.

**Comment by kristofeI** [comment]
My suggestion comes from the same sentiment:
**Signals are a big point of confusion in the community.**
Although descriptions i-game are rich and detailed (also in Polish version), I understood the signals (but I'm also not 100% sure) only after I read wiki article. Maybe add some image examples in-game? I'm not sure, but signals descriptions certainly need more clarification.

**Comment by victorleblais** [comment]
When building signals you now have arrows indicating the signal's status:
![image](https://user-images.githubusercontent.com/4365075/115538015-b8dc2d80-a29b-11eb-9449-d05d4270b0be.png)

Signal block visualisation is something that is planned on the roadmap:
https://voxeltycoon.xyz/roadmap
![image](https://user-images.githubusercontent.com/4365075/115538088-cf828480-a29b-11eb-9ac9-4c6ffd4d5541.png)
