### ISSUE TITLE
option to lock the mouse cursor on the game window

### ISSUE THREAD

**Issue by JaquesGelee** [voxeltycoon/suggestions#91]
When using 2 screens the mouse will move over to the other screen when reaching the end of the other one. Makes it impossible to scroll on the border to one side. Happens in Full screen mode and windowed mode. 
There should be an option to lock the mouse to the game screen.

**Comment by victorleblais** [comment]
This behavior should be **optional**. I'm using multiple monitors as well and I simply hate when games take control of your cursor without any option do to otherwise.

**Comment by JaquesGelee** [comment]
Oh, i was assuming this goes without saying.Of course i meant it to be optional. 
I edited it in m original comment.

**Comment by andrewpey** [comment]
Done in [0.79](https://voxeltycoon.xyz/changelog#0.79).
