### ISSUE TITLE
Company Locate Button

### ISSUE THREAD

**Issue by j0nas500** [voxeltycoon/suggestions#95]
It would be nice to have a button on the company popup that shows the location of the company.

**Comment by victorleblais** [comment]
What do you mean by "Location of the company"?

**Comment by j0nas500** [comment]
In the notifications above, for example, the following message appears: "Town X now accepts timber" Clicking on the notification displays the location of the company and the company popup.
If I'm in the process of doing something else, I leave the company popup open and after I have time to do so I devote myself to the company, but then I don't know anymore to which city the company is located and it would be nice if there is a "Show location" button in the company popup to find the company again by moving the map to it, as it is already the case with the notifications.

**Comment by victorleblais** [comment]
Clicking on the icon in the business' title bar now moves the camera to the building's location
![image](https://user-images.githubusercontent.com/4365075/115536980-a1e90b80-a29a-11eb-9f0e-45fdaf25ccb4.png)
